config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create]

  namespace :admin do
    resources :unpublished_pages, only: [:index]
    resources :page_uploads, only: [:create]
    resources :partial_publications, only: [:create]
    resources :publications, only: [:create]
  end

  resources :pages, param: :position, only: [:show]

  # FIXME: Develop proper arc and story management features so we can uncomment
  #        this.
  # resources :stories, param: :slug, only: [:index, :show] do
  #   resources :pages, params: :position, controller: 'story_pages', only: [:show]

  #   resources :arcs, param: :slug, only: [:show] do
  #     resources :pages, params: :position, controller: 'arc_pages', only: [:show]
  #   end
  # end
end

app/models/arc.rb
# == Schema Information
#
# Table name: arcs
#
#  id         :bigint           not null, primary key
#  name       :string
#  position   :bigint
#  url_slug   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  story_id   :bigint           not null
#
# Indexes
#
#  index_arcs_on_story_id  (story_id)
#
# Foreign Keys
#
#  fk_rails_...  (story_id => stories.id)
#

class Arc < ApplicationRecord
  include Slugged, Covered

  belongs_to :story
  has_many :publications
  has_many :pages, through: :publications do
    def find_page(position)
      PagePosition.where(page: self).find_by!(
        arc_position: position,
        arc_id: proxy_association.owner.id).page
    end
  end

  validates_presence_of :position, :name

  scope :published, -> { joins(:publications).merge(Publication.published) }
end

app/controllers/admin/unpublished_pages_controller.rb
class Admin::UnpublishedPagesController < Admin::BaseController
  def index
    @pages = Page.unpublished
  end
end

app/views/admin/unpublished_pages/index.html.erb
<%= header do %>
  <h2>
    Unpublished pages
  </h2>
  <div>
    <div data-target="interpolation.text">There's {{selection.count}} selected</div>
    <%= submit_tag "Create update",
                    'data-target': 'toggle.hide event-forwarder.source',
                    'data-action': 'click->event-forwarder#transfer',
                    'data-toggle-source': 'interpolation',
                    'data-event-forwarder-id': 'publicationCreation',
                    'data-event-forwarder-hide': true
                  %>
  </div>
<% end %>

<div class="card-list" data-controller="selection">
  <%= render partial: 'page_card',
             collection: @pages,
             as: :page,
             locals: { selectable: true } %>

  <%= form_tag admin_partial_publications_path, remote: true do %>
    <%= select_tag 'page_ids',
                    options_from_collection_for_select(@pages, :id, :created_at),
                    multiple: true, 'data-target': 'selection.selector' %>
    <%= submit_tag "Create update",
                   'data-target': 'event-forwarder.destination',
                   'data-event-forwarder-id': 'publicationCreation' %>
  <% end %>
</div>